import { OrderStatus } from "@/lib/enums/order-status.enum";
import { Order } from "@/lib/types/order";

export const orders: Order[] = [
  {
    _id: "1001",
    createdAt: new Date(),
    updatedAt: new Date(),
    receiver: {
      name: "string",
      phone: "string",
      address: "string",
      zipcode: "string",
      country: "string",
      state: "string",
      city: "string",
    },
    status: OrderStatus.Delivered,
    totalPrice: 270000,
  },
  {
    _id: "1002",
    createdAt: new Date(),
    updatedAt: new Date(),
    receiver: {
      name: "string",
      phone: "string",
      address: "string",
      zipcode: "string",
      country: "string",
      state: "string",
      city: "string",
    },
    status: OrderStatus.Paid,
    totalPrice: 270000,
  },
  {
    _id: "1003",
    createdAt: new Date(),
    updatedAt: new Date(),
    receiver: {
      name: "string",
      phone: "string",
      address: "string",
      zipcode: "string",
      country: "string",
      state: "string",
      city: "string",
    },
    status: OrderStatus.AwaitingPayment,
    totalPrice: 270000,
  },
  {
    _id: "1004",
    createdAt: new Date(),
    updatedAt: new Date(),
    receiver: {
      name: "string",
      phone: "string",
      address: "string",
      zipcode: "string",
      country: "string",
      state: "string",
      city: "string",
    },
    status: OrderStatus.Failed,
    totalPrice: 270000,
  },
  {
    _id: "1005",
    createdAt: new Date(),
    updatedAt: new Date(),
    receiver: {
      name: "string",
      phone: "string",
      address: "string",
      zipcode: "string",
      country: "string",
      state: "string",
      city: "string",
    },
    status: OrderStatus.Canceled,
    totalPrice: 270000,
  },
];
