import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";
import TelegramIcon from "@/components/icons/Telegram";
import InstagramIcon from "@/components/icons/Instagram";
import YoutubeIcon from "@/components/icons/Youtube";
import Topbar from "@/components/Topbar";

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazirmatn.className} bg-light-gray`} dir="rtl">
        <Topbar />

        <header className="bg-white sticky top-0 shadow-sm">
          <Navbar />
        </header>

        <main className="container mx-auto px-3">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
